config/routes.rb
Rails.application.routes.draw do

  # See how all your routes lay out with "rake routes".

  resources :tickets do
    post :check_in
    post :check_out
  end

  post '/check_in_with_new', to: "tickets#check_in_with_new"
  root 'tickets#index'
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  scope :checked_in, -> { where.not(checked_in_at: nil) }
  scope :checked_in_today, -> { where(checked_in_at: Time.now.beginning_of_day..Time.now.end_of_day) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @query = params[:query] unless params[:query].blank?
    if (@query and @query.length > 2)
      @tickets = Ticket.ransack(booking_id_eq: @query,
                                name_cont: @query,
                                pseudonym_cont: @query,
                                email_cont: @query,
                                password_cont: @query,
                                m: 'or')
                       .result(distinct: true)
    else
      @tickets = []
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    @ticket.update(params[:ticket].permit(:notes, :price))
    if params[:ticket][:price].present?
      @ticket.update_attribute(:paid, true)
      @ticket.update_attribute(:paid_at_checkin, true)
      check_in
      return
    end
    redirect_to @ticket
  end

  def new
    if Settings.new_ticket and Settings.new_ticket.defaults
      defaults = Settings.new_ticket.defaults.to_hash
    else
      defaults = {}
    end

    @ticket = Ticket.new(defaults)
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if Settings.new_ticket and Settings.new_ticket.check_in_after_create
      @ticket.checked_in_at = Time.now
    end

    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def check_in
    @ticket ||= Ticket.find(params[:ticket_id])
    @ticket.update_attribute(:checked_in_at, Time.now)
    if @ticket.role && Settings.roles[@ticket.role]
      flash_type = Settings.roles[@ticket.role].checked_in_flash_type || 'success'
      flash_message = Settings.roles[@ticket.role].checked_in_flash_message || 'Checked in successfully.'
    else
      flash_type = 'success'
      flash_message = 'Checked in successfully.'
    end
    flash = {}
    flash[flash_type] = flash_message
    redirect_to @ticket , flash: flash
  end

  def check_out
    @ticket = Ticket.find(params[:ticket_id])
    @ticket.update_attribute(:checked_in_at, nil)
    redirect_to @ticket
  end

  def ticket_params
    params.require(:ticket).permit(:name, :pseudonym, :email, :password, :price, :role, :notes, :created_by)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {
      success: "alert-success",
      error: "alert-danger",
      recaptcha_error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[flash_type.to_sym] || flash_type.to_s
  end

  def yes_no(b)
    b ? t('bool_yes') : t('bool_no')
  end

end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %a.navbar-brand{:href => "#{root_path}"} #{Settings.brand_name}
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = form_tag(tickets_path, method: :get, role: "search", class: "navbar-form navbar-left") do
            .form-group
              %input.form-control{:name => "query", placeholder: "Search", autofocus: "true", id: "query-field" }
              %button.btn.btn-default{:type => "submit"} Submit

      -unless Settings.hide_stats
        %ul.nav.navbar-nav.navbar-right
          %li
            %p.navbar-text
              #{Ticket.checked_in.count} checked in total

          %li
            %p.navbar-text
              #{Ticket.checked_in_today.count} checked in today

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title KassaBlanca
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      -if flash.any?
        .row
          .col-md-12
            .flash
              -flash.each do |msg_type, message|
                %div{ class: "alert #{bootstrap_class_for(msg_type)} fade in", role: "alert" }
                  %button.close{ data: { dismiss: 'alert' }} ×
                  %span=message
      = render 'layouts/nav'
      = yield

app/views/tickets/index.html.haml
-if @query
  =button_to tickets_path, class: "btn btn-info", style: "float:right", method: :get do
    %span.glyphicon.glyphicon-remove
    Clear filter
  %h3= "Tickets matching '#{@query}'"

  -if @tickets.any?
    %table.table.table-striped
      %thead
        %tr
          %th ID
          %th Name
          %th Email
          %th Checked In
          %th Role
          %th
      -@tickets.each do |ticket|
        %tr
          %th=ticket.booking_id
          %td=ticket.pseudonym.blank? ? ticket.name : ticket.pseudonym
          %td=ticket.email
          %td
            -if ticket.checked_in_at
              %span.glyphicon.glyphicon-ok
          %td
            -if ticket.role
              %span.label.label-warning
                =ticket.role.capitalize
          %td
            =link_to "Details", ticket
  -else
    %h4= "No matches"

-else
  %h3 No query
  %h4 Go search!

app/views/tickets/new.html.haml
.row
  .col-md-3
  .col-md-6
    =simple_form_for @ticket do |f|
      .panel.panel-default
        .panel-heading
          %h3.panel-title New ticket

        .panel-body
          =f.input :name
          =f.input :pseudonym
          =f.input :email
          =f.input :password
          =f.input :price
          =f.input :role
          =f.input :notes
          =f.input :created_by

        .panel-footer
          .form-actions
            =f.submit "Create ticket", class: 'btn btn-primary'
            =link_to "Cancel", root_path, class: 'btn'

app/views/tickets/show.html.haml
=button_to tickets_path, class: "btn btn-info", style: "float:right", method: :get do
  %span.glyphicon.glyphicon-arrow-left
  Back to all tickets
%h3= "Ticket ##{@ticket.booking_id} (#{@ticket.id})"

.well
  .row
    .col-md-2
      %strong Booking ID
    .col-md-3
      =@ticket.booking_id
  .row
    .col-md-2
      %strong Pseudonym
    .col-md-3
      =@ticket.pseudonym
  .row
    .col-md-2
      %strong Name
    .col-md-3
      =@ticket.name
  .row
    .col-md-2
      %strong Email
    .col-md-3
      =@ticket.email
  .row
    .col-md-2
      %strong Password
    .col-md-3
      =@ticket.password
  .row
    .col-md-2
      %strong Created by
    .col-md-3
      =@ticket.created_by

-unless @ticket.role.blank?
  .well
    .row
      .col-md-2
        %strong Role
      .col-md-3
        %h4
          %span.label.label-warning
            =@ticket.role.capitalize

.well
  .row
    .col-md-2
      %strong Payment
    .col-md-3
      .row
        .col-md-6
          =@ticket.price
          EUR
        .col-md-4
          %h4
            -if @ticket.paid?
              %span.glyphicon.glyphicon-ok
            -else
              %span.label.label-danger
                Not Paid

.well
  .row
    -if @ticket.checked_in_at?
      .col-md-2
        %strong Checked In
      .col-md-3
        .row
          .col-md-6
            =l @ticket.checked_in_at, format: :short
          .col-md-4
            =button_to "Check Out", ticket_check_out_path(@ticket), class: "btn btn-default btn-xs"
    -else
      -if @ticket.paid?
        .col-md-5
          =button_to "Check In Now", ticket_check_in_path(@ticket), class: "btn btn-warning btn-lg"
      -else
        .col-md-8
          =form_for @ticket do |f|
            .row
              .col-md-2
                %strong Paid amount
              .col-md-3
                .form-group
                  =f.text_field :price, class: "form-control"
              .col-md-3
                .form-group
                  =f.submit "Check in with payment", class: "btn btn-primary btn-default"

  .row
    .col-md-12

.well
  =form_for @ticket do |f|
    .row
      .col-md-2
        %strong Notes
      .col-md-3
        .form-group
          =f.text_area :notes, size: "200x10", class: "form-control"
      .col-md-3
        .form-group
          =f.submit "Save", class: "btn btn-primary btn-default"